// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package sqlcgen

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1 AS status
`

func (q *Queries) Ping(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, ping)
	var status int64
	err := row.Scan(&status)
	return status, err
}
