// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type Color struct {
	ID        int64         `json:"id"`
	Hex       string        `json:"hex"`
	R         sql.NullInt64 `json:"r"`
	G         sql.NullInt64 `json:"g"`
	B         sql.NullInt64 `json:"b"`
	CreatedAt time.Time     `json:"created_at"`
}

type File struct {
	ID                int64           `json:"id"`
	Uid               string          `json:"uid"`
	UserID            int64           `json:"user_id"`
	Name              string          `json:"name"`
	Path              sql.NullString  `json:"path"`
	Type              string          `json:"type"`
	FileMd5           string          `json:"file_md5"`
	Size              int64           `json:"size"`
	Key               string          `json:"key"`
	Extension         sql.NullString  `json:"extension"`
	Width             sql.NullInt64   `json:"width"`
	Height            sql.NullInt64   `json:"height"`
	Blurhash          sql.NullString  `json:"blurhash"`
	Arthash           sql.NullString  `json:"arthash"`
	ArthashCodec      sql.NullString  `json:"arthash_codec"`
	Lng               sql.NullFloat64 `json:"lng"`
	Lat               sql.NullFloat64 `json:"lat"`
	Country           sql.NullString  `json:"country"`
	CountryCode       sql.NullString  `json:"country_code"`
	Province          sql.NullString  `json:"province"`
	City              sql.NullString  `json:"city"`
	District          sql.NullString  `json:"district"`
	Address           sql.NullString  `json:"address"`
	Altitude          sql.NullFloat64 `json:"altitude"`
	TakenAt           sql.NullTime    `json:"taken_at"`
	DeviceMake        sql.NullString  `json:"device_make"`
	DeviceModel       sql.NullString  `json:"device_model"`
	LensModel         sql.NullString  `json:"lens_model"`
	FNumber           sql.NullString  `json:"f_number"`
	ExposureTime      sql.NullString  `json:"exposure_time"`
	Iso               sql.NullInt64   `json:"iso"`
	FocalLength       sql.NullString  `json:"focal_length"`
	ExifRaw           []byte          `json:"exif_raw"`
	Duration          sql.NullFloat64 `json:"duration"`
	Codec             sql.NullString  `json:"codec"`
	Bitrate           sql.NullInt64   `json:"bitrate"`
	FrameRate         sql.NullFloat64 `json:"frame_rate"`
	VideoMetadata     []byte          `json:"video_metadata"`
	TranscodingTaskID sql.NullString  `json:"transcoding_task_id"`
	IsPrivate         bool            `json:"is_private"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type FileColor struct {
	ID         int64           `json:"id"`
	FileID     int64           `json:"file_id"`
	ColorID    int64           `json:"color_id"`
	IsPrimary  bool            `json:"is_primary"`
	Rank       int64           `json:"rank"`
	Percentage sql.NullFloat64 `json:"percentage"`
	CreatedAt  time.Time       `json:"created_at"`
}

type MultipartUpload struct {
	ID          int64          `json:"id"`
	UploadID    string         `json:"upload_id"`
	Key         string         `json:"key"`
	Md5         string         `json:"md5"`
	FileName    string         `json:"file_name"`
	FileSize    int64          `json:"file_size"`
	ContentType sql.NullString `json:"content_type"`
	TotalParts  int64          `json:"total_parts"`
	ChunkSize   int64          `json:"chunk_size"`
	UserID      sql.NullInt64  `json:"user_id"`
	Status      string         `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Permission struct {
	ID          int64          `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	SpaceID     int64          `json:"space_id"`
	Position    int64          `json:"position"`
	Value       int64          `json:"value"`
	Module      sql.NullString `json:"module"`
	IsActive    bool           `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type PermissionSpace struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsActive    bool           `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Role struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsActive    bool           `json:"is_active"`
	IsSystem    bool           `json:"is_system"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type RolePermission struct {
	ID           int64     `json:"id"`
	RoleID       int64     `json:"role_id"`
	PermissionID int64     `json:"permission_id"`
	SpaceID      int64     `json:"space_id"`
	Value        int64     `json:"value"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type TranscodingTask struct {
	ID             int64          `json:"id"`
	TaskID         string         `json:"task_id"`
	FileID         sql.NullInt64  `json:"file_id"`
	SourceUrl      string         `json:"source_url"`
	WebhookUrl     sql.NullString `json:"webhook_url"`
	Provider       string         `json:"provider"`
	Status         string         `json:"status"`
	Resolutions    []byte         `json:"resolutions"`
	ExternalJobIds []byte         `json:"external_job_ids"`
	Results        []byte         `json:"results"`
	ErrorMsg       sql.NullString `json:"error_msg"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	CompletedAt    sql.NullTime   `json:"completed_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
}

type UploadedPart struct {
	ID         int64     `json:"id"`
	UploadID   string    `json:"upload_id"`
	PartNumber int64     `json:"part_number"`
	ETag       string    `json:"e_tag"`
	Size       int64     `json:"size"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID               int64          `json:"id"`
	Uid              string         `json:"uid"`
	LpID             string         `json:"lp_id"`
	Username         sql.NullString `json:"username"`
	Mobile           sql.NullString `json:"mobile"`
	Email            sql.NullString `json:"email"`
	OpenID           sql.NullString `json:"open_id"`
	Password         sql.NullString `json:"password"`
	AvatarFileID     sql.NullInt64  `json:"avatar_file_id"`
	BackgroundFileID sql.NullInt64  `json:"background_file_id"`
	Sex              int64          `json:"sex"`
	Birthday         sql.NullTime   `json:"birthday"`
	City             sql.NullString `json:"city"`
	Job              sql.NullString `json:"job"`
	Company          sql.NullString `json:"company"`
	Signature        sql.NullString `json:"signature"`
	Website          sql.NullString `json:"website"`
	Freezed          bool           `json:"freezed"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type UserPermissionCach struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	SpaceID   int64     `json:"space_id"`
	Value     int64     `json:"value"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserRole struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	RoleID    int64     `json:"role_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type VideoVariant struct {
	ID        int64           `json:"id"`
	FileID    int64           `json:"file_id"`
	Quality   string          `json:"quality"`
	Key       string          `json:"key"`
	Format    string          `json:"format"`
	Size      sql.NullInt64   `json:"size"`
	Width     sql.NullInt64   `json:"width"`
	Height    sql.NullInt64   `json:"height"`
	Bitrate   sql.NullInt64   `json:"bitrate"`
	Fps       sql.NullInt64   `json:"fps"`
	Duration  sql.NullFloat64 `json:"duration"`
	CreatedAt time.Time       `json:"created_at"`
}
